function [Out] = rsh_rot_ivanic_p(i, a, b, l, R, Mprev)
  if (b == l)
    Out = sh_rot_index(R, i, 1) * ...
          sh_rot_index(Mprev, a, l - 1) - ...
          sh_rot_index(R, i, -1) * ...
          sh_rot_index(Mprev, a, -l + 1);
  else if (b == -l)
    Out = sh_rot_index(R, i, 1) * ...
          sh_rot_index(Mprev, a, -l + 1) + ...
          sh_rot_index(R, i, -1) * ...
          sh_rot_index(Mprev, a, l - 1);
  else
    Out = sh_rot_index(R, i, 0) * sh_rot_index(Mprev, a, b);
  end
end
